# Generated by Django 2.0.1 on 2018-01-16 14:12

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='activity_date')),
                ('studentCnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_text', models.CharField(max_length=200)),
                ('maxStudentCnt', models.IntegerField(default=0)),
                ('category_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('surname_text', models.CharField(max_length=200)),
                ('alias_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=200)),
                ('style_text', models.CharField(max_length=200)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_text', models.CharField(max_length=200)),
                ('timeStart', models.DateTimeField(verbose_name='time_start')),
                ('timeEnd', models.DateTimeField(verbose_name='time_end')),
            ],
        ),
        migrations.AddField(
            model_name='activitytimetable',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Coach'),
        ),
        migrations.AddField(
            model_name='activitytimetable',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Term'),
        ),
        migrations.AddField(
            model_name='activitydone',
            name='activityTimeTeble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ActivityTimeTable'),
        ),
        migrations.AddField(
            model_name='activitydone',
            name='coachReplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Coach'),
        ),
    ]
