# Generated by Django 2.0 on 2018-01-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180116_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='term',
            name='days_text',
        ),
        migrations.AddField(
            model_name='term',
            name='periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='day_array',
            field=models.ManyToManyField(to='polls.DayOfTheWeek'),
        ),
    ]
