# Generated by Django 2.0.1 on 2018-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180116_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='style_text',
        ),
        migrations.AlterField(
            model_name='term',
            name='timeEnd',
            field=models.TimeField(verbose_name='time_end'),
        ),
        migrations.AlterField(
            model_name='term',
            name='timeStart',
            field=models.TimeField(verbose_name='time_start'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='coach',
            name='category_array',
            field=models.ManyToManyField(to='polls.Category'),
        ),
    ]
