# Generated by Django 2.0.1 on 2018-01-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180118_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytimetable',
            name='category_text',
        ),
        migrations.AddField(
            model_name='activitytimetable',
            name='category_array',
            field=models.ManyToManyField(to='polls.Category'),
        ),
    ]
