# Generated by Django 2.0 on 2018-01-20 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180118_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourStart_time', models.TimeField()),
                ('hourEnd_time', models.TimeField()),
                ('dateStart_date', models.DateField(default=datetime.date.today, verbose_name='work_start_date')),
                ('dateEnd_date', models.DateField(default=datetime.date.today, verbose_name='work_end_date')),
                ('day_array', models.ManyToManyField(to='polls.DayOfTheWeek')),
            ],
        ),
        migrations.RenameField(
            model_name='activitydone',
            old_name='activityTimeTeble',
            new_name='activityTimeTeble_key',
        ),
        migrations.RenameField(
            model_name='activitydone',
            old_name='coachReplacement',
            new_name='coachReplacement_key',
        ),
        migrations.RenameField(
            model_name='activitydone',
            old_name='studentCnt',
            new_name='studentCnt_int',
        ),
        migrations.RenameField(
            model_name='activitytimetable',
            old_name='coach',
            new_name='coach_key',
        ),
        migrations.RenameField(
            model_name='activitytimetable',
            old_name='maxStudentCnt',
            new_name='maxStudentCnt_int',
        ),
        migrations.RenameField(
            model_name='activitytimetable',
            old_name='term',
            new_name='term_key',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='address',
            new_name='coachAddress_address',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='periodic',
            new_name='periodic_bool',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='timeEnd',
            new_name='timeEnd_time',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='timeStart',
            new_name='timeStart_time',
        ),
        migrations.AddField(
            model_name='activitytimetable',
            name='dateEnd_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date_end'),
        ),
        migrations.AddField(
            model_name='activitytimetable',
            name='dateStart_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date_start'),
        ),
        migrations.AlterField(
            model_name='activitydone',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='activity_date'),
        ),
    ]
