# Generated by Django 2.0 on 2018-01-20 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180120_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimetable',
            name='dateEnd_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='dateEnd_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='work_end_date'),
        ),
    ]
