# Generated by Django 2.0.1 on 2018-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180121_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_text',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dayoftheweek',
            name='day_text',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dayoftheweek',
            name='index_int',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
