# Generated by Django 2.0.1 on 2018-02-01 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180201_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoftheweek',
            name='index_int',
            field=models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
