# Generated by Django 2.0 on 2018-02-04 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180201_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativceCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeCodeUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(1939), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(79), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Voivodship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(2), polls.models.validate_even])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Country')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='voivodship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Voivodship'),
        ),
        migrations.AddField(
            model_name='administrativcecommunity',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.County'),
        ),
        migrations.AddField(
            model_name='administrativcecommunity',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AdministrativeCodeUnitType'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Country'),
        ),
    ]
