# Generated by Django 2.0.1 on 2018-02-06 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180204_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code_int', models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
        migrations.RenameField(
            model_name='administrativcecommunity',
            old_name='code',
            new_name='code_int',
        ),
        migrations.RenameField(
            model_name='administrativcecommunity',
            old_name='county',
            new_name='county_key',
        ),
        migrations.RenameField(
            model_name='administrativcecommunity',
            old_name='name',
            new_name='name_text',
        ),
        migrations.RenameField(
            model_name='administrativcecommunity',
            old_name='unit_type',
            new_name='unit_type_key',
        ),
        migrations.RenameField(
            model_name='administrativecodeunittype',
            old_name='code',
            new_name='code_int',
        ),
        migrations.RenameField(
            model_name='administrativecodeunittype',
            old_name='name',
            new_name='name_text',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='code',
            new_name='code_int',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='voivodship',
            new_name='voivodship_key',
        ),
        migrations.RenameField(
            model_name='voivodship',
            old_name='code',
            new_name='code_int',
        ),
        migrations.RenameField(
            model_name='voivodship',
            old_name='country',
            new_name='country_key',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='county',
            name='name',
        ),
        migrations.RemoveField(
            model_name='voivodship',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='community_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.AdministrativceCommunity'),
        ),
        migrations.AddField(
            model_name='address',
            name='flat_nr_int',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='address',
            name='house_nr_int',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='address',
            name='street_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='code_alpha_2_text',
            field=models.CharField(default='', max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code_alpha_3_text',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code_int',
            field=models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='country',
            name='name_text',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='county',
            name='name_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='voivodship',
            name='name_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.PostalCode'),
        ),
    ]
